kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  ports:
    # Delete the old port
    - port: 8666
      targetPort: 8080
      protocol: TCP
      $patch: delete
    # Add our new port
    - port: 8668
      targetPort: 8080
      protocol: TCP
      name: main
